export const users = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    role: 'admin',
    status: 'online',
    joiningDate: '2023-01-15',
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    role: 'member',
    status: 'offline',
    joiningDate: '2022-12-10',
  },
  {
    id: '3',
    name: 'Catherine Lee',
    email: 'catherine.lee@example.com',
    role: 'guest',
    status: 'dnd',
    joiningDate: '2023-04-20',
  },
  {
    id: '4',
    name: 'Daniel Kim',
    email: 'daniel.kim@example.com',
    role: 'admin',
    status: 'offline',
    joiningDate: '2023-03-05',
  },
  {
    id: '5',
    name: 'Emma Brown',
    email: 'emma.brown@example.com',
    role: 'member',
    status: 'online',
    joiningDate: '2022-11-08',
  },
  {
    id: '6',
    name: 'Frank Green',
    email: 'frank.green@example.com',
    role: 'guest',
    status: 'dnd',
    joiningDate: '2023-05-15',
  },
  {
    id: '7',
    name: 'Grace Park',
    email: 'grace.park@example.com',
    role: 'admin',
    status: 'online',
    joiningDate: '2022-10-01',
  },
  {
    id: '8',
    name: 'Henry White',
    email: 'henry.white@example.com',
    role: 'member',
    status: 'offline',
    joiningDate: '2023-02-17',
  },
  {
    id: '9',
    name: 'Isabella Harris',
    email: 'isabella.harris@example.com',
    role: 'guest',
    status: 'dnd',
    joiningDate: '2023-03-28',
  },
  {
    id: '10',
    name: 'Jack Martinez',
    email: 'jack.martinez@example.com',
    role: 'admin',
    status: 'online',
    joiningDate: '2022-09-20',
  },
  {
    id: '11',
    name: 'Karen Walker',
    email: 'karen.walker@example.com',
    role: 'member',
    status: 'offline',
    joiningDate: '2023-01-30',
  },
  {
    id: '12',
    name: 'Leonardo Scott',
    email: 'leonardo.scott@example.com',
    role: 'guest',
    status: 'online',
    joiningDate: '2022-12-23',
  },
  {
    id: '13',
    name: 'Mia Lopez',
    email: 'mia.lopez@example.com',
    role: 'admin',
    status: 'dnd',
    joiningDate: '2023-04-12',
  },
  {
    id: '14',
    name: 'Nathan Young',
    email: 'nathan.young@example.com',
    role: 'member',
    status: 'online',
    joiningDate: '2022-11-18',
  },
  {
    id: '15',
    name: 'Olivia Clark',
    email: 'olivia.clark@example.com',
    role: 'guest',
    status: 'offline',
    joiningDate: '2023-02-04',
  },
  {
    id: '16',
    name: 'Paul Carter',
    email: 'paul.carter@example.com',
    role: 'admin',
    status: 'dnd',
    joiningDate: '2023-05-21',
  },
  {
    id: '17',
    name: 'Quinn Lewis',
    email: 'quinn.lewis@example.com',
    role: 'member',
    status: 'online',
    joiningDate: '2022-10-05',
  },
  {
    id: '18',
    name: 'Rachel Hall',
    email: 'rachel.hall@example.com',
    role: 'guest',
    status: 'dnd',
    joiningDate: '2023-03-11',
  },
  {
    id: '19',
    name: 'Samuel King',
    email: 'samuel.king@example.com',
    role: 'admin',
    status: 'offline',
    joiningDate: '2022-12-14',
  },
  {
    id: '20',
    name: 'Tina Moore',
    email: 'tina.moore@example.com',
    role: 'member',
    status: 'online',
    joiningDate: '2023-01-08',
  },
] as const;
